alias chrome='google-chrome-stable'
alias uio='ssh -YC bendiksa@login.ifi.uio.no'
alias grep='grep -E --color=auto'
alias ls='ls -Gp'
alias l='ls -CF'
alias ll='ls -alF'
alias certify='codesign -f -s "Bendik Samseth" --deep'
alias weather='curl -4 wttr.in'
alias vim='/usr/local/Cellar/vim/8.0.0002/bin/vim'
alias nosetests='/usr/local/bin/nosetests-3.4'
